### ISSUE TITLE
[SQL과 NOSQL의 차이] NoSQL 스키마 관련

### ISSUE THREAD

**Issue by ykk2006** [kim6394/tech-interview-for-developer#38]
NoSQL에서 스키마가 없다고 하셨는데 최근 MongDB 컨퍼런스에서 "NoSQL에서 스키마가 없다는 말은 잘못된 말이다! 스키마를 RDBMS에 비해 덜 신경써도 될 뿐 중요하다" 라는 이야기를 들었습니다. 이에 관한 확인 부탁드립니다.

**Comment by kim6394** [comment]
이슈 감사합니다~! 자세한 내용을 확인한 뒤에 검토하여 수정하겠습니다😄
