### ISSUE TITLE
퀵 정렬(Quick Sort) 관련

### ISSUE THREAD

**Issue by qwer9412** [kim6394/tech-interview-for-developer#40]
퀵 정렬이 최악의 시간복잡도를 가지는 경우는 역순 뿐만 아니라 완전히 정렬 되어 있는 경우도 해당될 것 같습니다!

두 부분으로 분할 했을 때 한 쪽으로만 데이터가 몰리는 경우가 n2의 시간복잡도를 가질 경우인데
역순이랑 정렬 되어 있는 경우 모두 해당할 것 같네요!

**Comment by kim6394** [comment]
안녕하세요! 답변이 늦었습니다. 기존 문서의 설명이 부족했습니다. 역순에 최악의 경우가 되는 것이 아니라, 피벗 값이 최소나 최대값으로 지정돼 파티션이 나누어지지 않은 경우로 수정했습니다. 감사합니다!😄
