### ISSUE TITLE
README 에서 [C++] 가상 함수(Virtual Function) 부분 주소가 잘못되어있습니다.

### ISSUE THREAD

**Issue by inspire12** [kim6394/tech-interview-for-developer#50]
- [[C++] 가상 함수(Virtual Function)](https://github.com/kim6394/tech-interview-for-developer/blob/master/Language/%5Bcpp%5D%20%EA%B0%80%EC%83%81%20%ED%95%A8%EC%88%98(virtual%20function).md)

아마 cpp -> c++ 바꾸면서 경로가 달라진 거 같은데 

- [[C++] 가상 함수(Virtual Function)](https://github.com/kim6394/tech-interview-for-developer/blob/master/Language/%5BC%2B%2B%5D%20%EA%B0%80%EC%83%81%20%ED%95%A8%EC%88%98(virtual%20function).md)
로 바꾸시면 좋을 거 같습니다. 
내용이 알차서 정독중입니다. ㅎㅎ

**Comment by kim6394** [comment]
수정 완료했습니다! 감사합니다~😄
